### ISSUE TITLE
`java.net.ProtocolException: Server redirected too many times` in `sbt ci-release`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-serialization-helper#410]
First observed in June 2024 on `main` branch builds ([example](https://github.com/VirtusLab/akka-serialization-helper/actions/runs/9543673567/job/26301494480)), `publish-maven-artifacts` job.

```
[error] java.net.ProtocolException: Server redirected too many  times (20)
[error] 	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor22.newInstance(Unknown Source)
[error] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[error] 	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2002)
[error] 	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1997)
[error] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1996)
[error] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1558)
[error] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1542)
[error] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[error] 	at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:288)
[error] 	at org.apache.ivy.util.url.URLHandlerDispatcher.upload(URLHandlerDispatcher.java:82)
[error] 	at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
[error] 	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:407)
...
```

This is due to underlying 401 Unauthorized on requests:

```
PUT https://oss.sonatype.org/content/repositories/snapshots/org/virtuslab/ash/annotation_2.12/0.7.3%2B76-2f44d156%2B20240617-2010-SNAPSHOT/annotation_2.12-0.7.3%2B76-2f44d156%2B20240617-2010-SNAPSHOT.pom (Authorization: Basic ...)

HTTP/1.1 401 Content access is protected by token (WWW-Authenticate: BASIC realm="Sonatype Nexus Repository Manager")
```

For the likely cause of this 401, see this [article published on the very same day as I write this issue](https://support.sonatype.com/hc/en-us/articles/360049469534-401-Content-access-is-protected-by-token-when-accessing-repositories). It's likely that Sonatype started requiring `token name code:token pass code` pairs in Basic authentication instead of the usual `user:password` pair ([another article](https://help.sonatype.com/en/user-tokens.html#using-your-user-token-for-repository-authentication)).

**Comment by PawelLipski** [comment]
Circumvented by removing the snapshot release step from CI ;p
