### ISSUE TITLE
`NullPointerException` with `io.circe.generic.semiauto.deriveXxx`

### ISSUE THREAD

**Issue by AltiorRonan** [VirtusLab/akka-serialization-helper#436]
I just add this code to use Circe Semi-automatic Derivation (https://circe.github.io/circe/codecs/semiauto-derivation.html):

```
object GenericClass {
  import io.circe._

  implicit def GenericClassCiEnc[A <: CirceSerializabilityTrait: Encoder, B <: CirceSerializabilityTrait: Encoder]
      : Encoder[GenericClass[A, B]] = io.circe.generic.semiauto.deriveEncoder[GenericClass[A, B]]

  implicit def GenericClassCiDec[A <: CirceSerializabilityTrait: Decoder, B <: CirceSerializabilityTrait: Decoder]
      : Decoder[GenericClass[A, B]] = io.circe.generic.semiauto.deriveDecoder[GenericClass[A, B]]
}
```

Now when I launch this test: `sbt "++ 2.13.15" "testOnly org.virtuslab.ash.circe.CirceAkkaSerializerSpec"` 

❌ I got an NPE:
```
java.lang.NullPointerException was thrown.
java.lang.NullPointerException
	at org.virtuslab.ash.circe.data.GenericClass$anon$lazy$macro$11$1$$anon$1.encodeObject(GenericClass.scala:10)
	at org.virtuslab.ash.circe.data.GenericClass$anon$lazy$macro$11$1$$anon$1.encodeObject(GenericClass.scala:10)
	at io.circe.generic.encoding.DerivedAsObjectEncoder$$anon$1.encodeObject(DerivedAsObjectEncoder.scala:29)
	at io.circe.Encoder$AsObject.apply(Encoder.scala:904)
	at io.circe.Encoder$AsObject.apply$(Encoder.scala:904)
	at io.circe.generic.encoding.DerivedAsObjectEncoder.apply(DerivedAsObjectEncoder.scala:22)
	at org.virtuslab.ash.circe.CirceAkkaSerializer.toBinary(CirceAkkaSerializer.scala:75)
	at akka.serialization.Serialization.$anonfun$serialize$2(Serialization.scala:167)
	at scala.util.Try$.apply(Try.scala:217)
	at akka.serialization.Serialization.$anonfun$serialize$1(Serialization.scala:167)
	at akka.serialization.Serialization.withTransportInformation(Serialization.scala:157)
	at akka.serialization.Serialization.serialize(Serialization.scala:166)
	at akka.actor.testkit.typed.scaladsl.SerializationTestKit.roundtrip(SerializationTestKit.scala:55)
	at akka.actor.testkit.typed.scaladsl.SerializationTestKit.verifySerialization(SerializationTestKit.scala:41)
	at akka.actor.testkit.typed.scaladsl.SerializationTestKit.verifySerialization(SerializationTestKit.scala:29)
	at org.virtuslab.ash.circe.CirceAkkaSerializerSpec.$anonfun$new$6(CirceAkkaSerializerSpec.scala:88)
```

Do you know what's the problem with this code ?

**Comment by PawelLipski** [comment]
I've just reproduced your issue, extra error details for the record:

```
- should serialize generic classes *** FAILED ***
  java.lang.NullPointerException: Cannot invoke "io.circe.Encoder.apply(Object)" because "this.circeGenericEncoderFora" is null
```

Lemme think of a fix 🤔 AFAICS semi-auto codecs are [included in the examples](https://github.com/search?q=repo%3AVirtusLab%2Fakka-serialization-helper%20semiauto&type=code) but not covered by tests, alas ☹️

**Comment by PawelLipski** [comment]
Actually... this is a somewhat synthetic situation when a custom serializer is provided for a test class 🤔 when `GenericClassCiEnc` and `GenericClassCiDec` are **not** provided in `object GenericClass`, then the implicits passed to `Register[GenericClass[CirceSerializabilityTrait, CirceSerializabilityTrait]]` in `org.virtuslab.ash.circe.CustomSerializer.codecs` resolve to:

<img width="1070" alt="image" src="https://github.com/user-attachments/assets/2d72b0a1-dfa5-486c-96fa-5bf57419b854" />

`importedDecoder` and `importedEncoder` come from `io.circe.LowPriorityDecoders` and `io.circe.LowPriorityEncoders`, respectively.

So... let's take a step back, what is your use case where you need to provide these custom de/encoder instead of relying on the defaults? 🤔

**Comment by ronanM** [comment]
I prefer use semi-auto de/encoder for compilation time.

(I also have this kind of problem on a fork, where I've replace Circe by PlayJson)

**Comment by PawelLipski** [comment]
> I also have this kind of problem on a fork, where I've replace Circe by PlayJson

Hmmm could you share this fork? it's surprising that the problem happens in PlayJson as well, it looks like sth Circe-specific 🤔
